---
title: "GA Senate Runoffs"
author: "Aaron Kessler & Bill Allison"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    # code_download: true
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(janitor)
library(plotly)
library(widgetframe)
library(scales)
library(zoo)
library(summarytools)
library(writexl)
library(tidycensus)
library(tigris)
library(sf)
library(leaflet)
library(tmap)
library(tmaptools)
library(RColorBrewer)
library(htmlwidgets)
library(htmltools)
library(widgetframe)
library(sp)
library(raster)
library(mapview)
library(scales)
library(viridis)
library(tidyverse)
options(tigris_class = "sf")
options(dplyr.summarise.inform = FALSE)


```


```{r dataload, include=FALSE, cache=TRUE}
#load data files created in step 01
actblue_contribs <- readRDS("processed_data/actblue_fecraw_contribs_postelex_GASEN.rds")
winred_contribs <- readRDS("processed_data/winred_fecraw_contribs_postelex_GASEN.rds")


#ensure that nothing slipped through during processing and we're just looking at 
#individual earmarked contributions
actblue_contribs <- actblue_contribs %>% 
  filter(
    entity_type == "IND", # only individual contributions
    is.na(memo_code), # remove memo lines
    contribution_purpose_descrip == "Earmark" # remove donations that are not for a specific candidate
  )

winred_contribs <- winred_contribs %>% 
  filter(
    entity_type == "IND", # only individual contributions
    is.na(memo_code), # remove memo lines
  )




```



## Totals

#### Actblue

```{r}

actblue_contribs %>% 
  group_by(ga_candidate) %>% 
  summarise(total_dollars = sum(contribution_amount), avg_amount = mean(contribution_amount), median_amount = median(contribution_amount)) 

```

#### WinRed
```{r}
winred_contribs %>% 
  group_by(ga_candidate) %>% 
  summarise(total_dollars = sum(contribution_amount), avg_amount = mean(contribution_amount), median_amount = median(contribution_amount)) 

```

###
## In-State vs. Out-of-State
  
  
**Dem overall totals**
```{r}

dem_inout <- actblue_contribs %>% 
  group_by(in_out_state) %>% 
  summarise(total_dollars = sum(contribution_amount)) %>% 
  ungroup()

dem_inout
```

**Dem totals by top states**
```{r}

dem_bystate <- actblue_contribs %>% 
  group_by(contributor_state) %>% 
  summarise(total_dollars = sum(contribution_amount)) %>% 
  arrange(desc(total_dollars)) %>% 
  ungroup() %>% 
  head(15)

dem_bystate
```


**Dem candidate totals**
```{r}

dem_inout_bycand <- actblue_contribs %>% 
  group_by(ga_candidate, in_out_state) %>% 
  summarise(total_dollars = sum(contribution_amount)) %>% 
  ungroup()

dem_inout_bycand


```

```{r}

#chart it out
d <- ggplot(dem_inout, aes(in_out_state, total_dollars)) + geom_col(fill = "darkblue") + coord_flip() +
  theme_minimal()

#add extra elements to the chart and convert to ggplotly
d2 <- d + labs(title = "Dems: In vs. Out of State",
               subtitle = "(Since Nov. 4th)",
               caption = "Source: Bloomberg Analysis, FEC",
               x ="", y = "") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.subtitle = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels=dollar) 

d2





```





```{r}

# The palette:
cbPalette <- c("#508104","#db8200")

d <- ggplot(data = dem_inout_bycand, aes(x = ga_candidate, y = total_dollars, fill = in_out_state)) +
  geom_col(position = "dodge") + coord_flip() + theme_minimal()

d2 <- d + labs(title="Dems Candidates: In vs. Out of State",
               subtitle = "(Since Nov. 4th)",
               caption = "Source: Source: Bloomberg Analysis, FEC",
               x ="", y = "") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.subtitle = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels=dollar) +
  scale_fill_manual(values=cbPalette) +
  theme(legend.title=element_blank())

d2



```


**GOP overall totals**
```{r}

gop_inout <- winred_contribs %>%
  group_by(in_out_state) %>%
  summarise(total_dollars = sum(contribution_amount)) %>%
  ungroup()

gop_inout
```

**GOP totals by top states**
```{r}

gop_bystate <- winred_contribs %>% 
  group_by(contributor_state) %>% 
  summarise(total_dollars = sum(contribution_amount)) %>% 
  arrange(desc(total_dollars)) %>% 
  ungroup() %>% 
  head(15)

gop_bystate
```



**GOP candidate totals**
```{r}

gop_inout_bycand <- winred_contribs %>%
  group_by(ga_candidate, in_out_state) %>%
  summarise(total_dollars = sum(contribution_amount)) %>%
  ungroup()

gop_inout_bycand


```


```{r}

#chart it out
d <- ggplot(gop_inout, aes(in_out_state, total_dollars)) + geom_col(fill = "darkred") + coord_flip() +
  theme_minimal()

#add extra elements to the chart and convert to ggplotly
d2 <- d + labs(title = "Republicans: In vs. Out of State",
               subtitle = "(Since Nov. 4th)",
               caption = "Source: Bloomberg Analysis, FEC",
               x ="", y = "") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.subtitle = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels=dollar)

d2





```





```{r}

# The palette:
cbPalette <- c("#508104","#db8200")

d <- ggplot(data = gop_inout_bycand, aes(x = ga_candidate, y = total_dollars, fill = in_out_state)) +
  geom_col(position = "dodge") + coord_flip() + theme_minimal()

d2 <- d + labs(title="Republican Candidates: In vs. Out of State",
               subtitle = "(Since Nov. 4th)",
               caption = "Source: Source: Bloomberg Analysis, FEC",
               x ="", y = "") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.subtitle = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels=dollar) +
  scale_fill_manual(values=cbPalette) +
  theme(legend.title=element_blank())

d2



```


# Zip Codes


```{r, include=FALSE}

# Prepare data

topzips_gop <- winred_contribs %>% 
  mutate(
    zip5 = str_sub(contributor_zip_code, 1, 5)
  ) %>% 
  group_by(zip5) %>% 
  summarise(sumtotal = sum(contribution_amount)) %>% 
  arrange(desc(sumtotal))

# topzips_gop


topzips_dem <- actblue_contribs %>% 
  mutate(
    zip5 = str_sub(contributor_zip_code, 1, 5)
  ) %>% 
  group_by(zip5) %>% 
  summarise(sumtotal = sum(contribution_amount)) %>% 
  arrange(desc(sumtotal))

# topzips_dem

#write to file
write_csv(topzips_gop, "output/topzips_gop_winred.csv")
write_csv(topzips_dem, "output/topzips_dem_actblue.csv")


### compare D and R in each zip ##

colnames(topzips_dem) <- c("zip_code", "demtotal")
colnames(topzips_gop) <- c("zip_code", "goptotal")

#join
zipcompare <- full_join(topzips_dem, topzips_gop)

#change nas to 0
zipcompare <- zipcompare %>% 
  replace(., is.na(.), 0)

#party with more
zipcompare <- zipcompare %>% 
  mutate(
    winner = ifelse(demtotal>goptotal, "D", "R"),
    advantage = abs(demtotal-goptotal)  
  )


### bring in the zipcode data table for adding names to zips 
zip_codes_lookup <- read_csv("zip_data/zip-codes-database-STANDARD.csv")

zip_codes_lookup <- zip_codes_lookup %>% 
  clean_names()

zip_codes_lookup <- zip_codes_lookup %>% 
  mutate(
    city = str_to_title(city),
    name = paste0(city, ", ", state),
    zipname = paste0(zip_code, " (", name, ")")
  ) %>% 
  select(zip_code, city, state, zipname)

#remove dups
zip_codes_lookup <- zip_codes_lookup %>% 
  distinct(zip_code, city, state, zipname)


#join to our table
zipcompare <- left_join(zipcompare, zip_codes_lookup)

#save table as rds for later use
saveRDS(zipcompare, "zip_data/zipcompare.rds")
# save as excel for sharing
write_xlsx(zipcompare, "output/zipcompare.xlsx")


```


**Top Zips for Democrats (ActBlue)**

```{r}

#pull out top 10 zips for the dems
dem10 <- zipcompare %>% 
  arrange(desc(demtotal)) %>% 
  head(15)

# dem10

#reorder factor to allow for descending bars
dem10 <- dem10 %>%
  mutate(zipname = fct_reorder(zipname, demtotal)) 

#export to file
write_csv(dem10, "output/dem10.csv")


#chart it out
d <- ggplot(dem10, aes(zipname, demtotal)) + geom_col(fill = "darkblue") + coord_flip() +
  theme_minimal()

#add extra elements to the chart and convert to ggplotly
d2 <- d + labs(title="GA Runoffs: Top ActBlue zip codes",
               # subtitle = "A subtitle",
               caption = "Source: FEC, Bloomberg Analysis",
               x ="", y = "") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels=dollar) 

d2



# dd <- ggplotly(d2) 
# 
# dd_nomenu <- dd %>% config(displayModeBar = FALSE)
# dd_nomenu
# 
# #save as embeddable format
# # htmlwidgets::saveWidget(frameableWidget(dd), 'demtopzip_plt.html')
# htmlwidgets::saveWidget(frameableWidget(dd_nomenu), 'demtopzip_chart_nm.html')
# 
# #save as RDS object
# saveRDS(dd_nomenu, "zip_data/demtopzip_chart_nm.rds")
```


**Top Zips for Republicans (WinRed)**

```{r}

#pull out top 10 zips for the gop
gop10 <- zipcompare %>% 
  arrange(desc(goptotal)) %>% 
  head(15)

# gop10

#reorder factor to allow for descending bars
gop10 <- gop10 %>%
  mutate(zipname = fct_reorder(zipname, goptotal)) 

#export to file
write_csv(gop10, "output/gop10.csv")


#chart it out
p <- ggplot(gop10, aes(zipname, goptotal)) + geom_col(fill = "darkred") + coord_flip() +
  theme_minimal()

#add titles and other extras
p2 <- p + labs(title="Ga Senate Runoffs: Top WinRed zip codes",
               # subtitle = "A subtitle",
               caption = "Source: FEC, Bloomberg Analysis",
               x ="", y = "") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels=dollar) 

p2

# pp <- ggplotly(p2) 
# 
# pp
# 
# pp_nomenu <- pp %>% config(displayModeBar = FALSE)
# pp_nomenu
# 
# #save as embeddable format
# # htmlwidgets::saveWidget(frameableWidget(pp), 'goptopzip_plt.html')
# htmlwidgets::saveWidget(frameableWidget(pp_nomenu), 'goptopzip_plt_nm.html')

#save as RDS object
# saveRDS(pp_nomenu, "zip_data/goptopzip_plt_nm.rds")




```

## Zip Maps

```{r}

#bring in comparison table created above
zipcompare <- readRDS("zip_data/zipcompare.rds")

head(zipcompare)
names(zipcompare)

zipcompare$GEOID <- zipcompare$zip_code

#remove any negative values
zipcompare <- zipcompare %>% 
  filter(demtotal >= 0,
         goptotal >= 0)

zipcompare <- zipcompare %>% 
  filter(!str_detect(GEOID, "^99"),
         !str_detect(GEOID, "^96"),
         !str_detect(GEOID, "^006"),
         !str_detect(GEOID, "^007"),
         !str_detect(GEOID, "^009")
           )


#### get zip code lat/long points from census gazeteer file
zip_points <- read_csv("zip_data/zip_points.csv", 
                       col_types = cols(ALAND = col_skip(), 
                                        ALAND_SQMI = col_skip(), AWATER = col_skip(), 
                                        AWATER_SQMI = col_skip()))

colnames(zip_points) <- c("GEOID", "lat", "lon")

#join data
zip_map <- inner_join(zipcompare, zip_points)

zip_map$winner <- as.factor(zip_map$winner)

#add dollar formatting
zip_map$demdisplay <- dollar(zip_map$demtotal)
zip_map$gopdisplay <- dollar(zip_map$goptotal)



#### MAPPING POINTS ##### ---------------------------------------

factpal <- colorFactor(c("blue","red"), zip_map$winner)

#labels
labs1 <- lapply(seq(nrow(zip_map)), function(i) {
  paste0( '<p>', 'Zip code: ', '<strong>', zip_map[i, "GEOID"], '</strong></p>',
          '<p></p>', 
          "Democrats: ", zip_map[i, "demdisplay"],
          '<p></p>', 
          "Republicans: ", zip_map[i, "gopdisplay"]
  ) 
})

m1 <- leaflet(zip_map) %>% 
  addTiles() %>%
  addCircles(lng = ~lon, lat = ~lat, weight = .4,
             stroke = FALSE, fillOpacity = .25,
             radius = ~sqrt(advantage) * 300, 
             fillColor = ~factpal(winner),
             label = lapply(labs1, HTML)
  ) %>%
  addControl("ActBlue vs. WinRed - GA Senate candidate contributions by zip code", position = "topright") 
# %>% 
#   setView(-96, 37.8, zoom=4) 

m1

#save to frameable file for CMS
htmlwidgets::saveWidget(frameableWidget(m1),'gasenate_actblue_vs_winred_zippoints.html')

# save as rds object
saveRDS(m1, "savedmap_zipcompare.rds")






```


```{r}

#### top zips for each party

t_gop <- zipcompare %>% 
  select(zip_code, total = goptotal) %>%
  mutate(party = "R") %>% 
  arrange(desc(total)) %>% 
  head(250)

t_dem <- zipcompare %>% 
  select(zip_code, total = demtotal) %>% 
  mutate(party = "D") %>% 
  arrange(desc(total)) %>% 
  head(250)

#combine
t_both <- bind_rows(t_dem, t_gop)

t_both

t_both %>% write_xlsx("output/t_both.xlsx")

```


```{r}




```


```{r}




```



